export const OPEN_WEATHER_URL = process.env.OPEN_WEATHER_URL;
export const OPEN_WEATHER_API_KEY = process.env.OPEN_WEATHER_API_KEY;
export const GOOGLE_APPLICATION_CREDENTIALS = process.env.FIREBASE_CONFIG;
