name: Docker Image CI

on:
  push:
    branches: [ "main" , "dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ericksaito --password-stdin
    
    - name: Build the Docker image
      run: docker build -f server/Dockerfile -t ghcr.io/ericksaito/mc855:$(date)
    
    - name: Tag
      run: docker tag ghcr.io/ericksaito/mc855:$(date) ghcr.io/ericksaito/mc855:dev

    - name: Push tag
      run: docker push ghcr.io/ericksaito/mc855:$(date)
    
    - name: Push dev
      run: docker push ghcr.io/ericksaito/mc855:dev